const contactTypes = {
	FETCH_CONTACTS_START: 'FETCH_CONTACTS_START',
	FETCH_CONTACTS_SUCCESS: 'FETCH_CONTACTS_SUCCESS',
	FETCH_CONTACTS_FAILURE: 'FETCH_CONTACTS_FAILURE'
};

export default contactTypes;